### ISSUE TITLE
iOS Support?

### ISSUE THREAD

**Issue by rvonkriegenbergh** [dhindrik/TinyMvvm#1]
Is this supposed to work on iOS? Overriding Initialize works for me on an Android device but it never gets called on an iOS device (iPhone 12, iOS 16.4.1)

**Comment by dhindrik** [comment]
Yes. There a no platform-specific code in the library so it should work. Is it possible for you to share a reproduction repo or at least share some code snippets with me?

**Comment by rvonkriegenbergh** [comment]
Never mind. I didn't set the BindingContext in that particular view. It didn't work on Android either. It works on both devices.
